-- Delivery zone radius (km) on the restaurant, for the checkout zone check.
ALTER TABLE restaurant
    ADD COLUMN restaurant_delivery_radius_km NUMERIC(6, 2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS restaurant_delivery_option (
                                                          config_id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                                          restaurant_id         INTEGER NOT NULL,
                                                          delivery_option       VARCHAR(30) NOT NULL,
    additional_fee        NUMERIC(12, 4) NOT NULL DEFAULT 0,
    time_modifier_mins    INTEGER NOT NULL DEFAULT 0,
    is_active             BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk__restaurant_delivery_option PRIMARY KEY (config_id),
    CONSTRAINT fk__restaurant_delivery_option__restaurant_id
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id) ON DELETE CASCADE,
    CONSTRAINT uq__restaurant_delivery_option__restaurant_id__delivery_option
    UNIQUE (restaurant_id, delivery_option),
    CONSTRAINT chk__restaurant_delivery_option__delivery_option
    CHECK (delivery_option IN ('DELIVERY', 'TAKEAWAY', 'IN_RESTAURANT')),
    CONSTRAINT chk__restaurant_delivery_option__additional_fee CHECK (additional_fee >= 0)
    );

CREATE INDEX idx__restaurant_delivery_option__restaurant_id
    ON restaurant_delivery_option (restaurant_id);

-- DEV seed: radius + options for the seeded restaurant so the endpoint is testable.
UPDATE restaurant SET restaurant_delivery_radius_km = 10.00
WHERE restaurant_name = 'Koshary El Tahrir';

INSERT INTO restaurant_delivery_option (restaurant_id, delivery_option, additional_fee, time_modifier_mins)
SELECT r.restaurant_id, v.delivery_option, v.additional_fee, v.time_modifier_mins
FROM restaurant r
         CROSS JOIN (VALUES
                         ('DELIVERY', 15.0000, 30),
                         ('TAKEAWAY',  0.0000,  0)
) AS v(delivery_option, additional_fee, time_modifier_mins)
WHERE r.restaurant_name = 'Koshary El Tahrir'
    ON CONFLICT (restaurant_id, delivery_option) DO NOTHING;