-- Add profile picture URL and account status to customer table
ALTER TABLE customer ADD COLUMN IF NOT EXISTS profile_picture_url VARCHAR(500);
ALTER TABLE customer ADD COLUMN IF NOT EXISTS account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE customer ADD CONSTRAINT chk_customer_account_status CHECK (account_status IN ('ACTIVE', 'DISABLED'));

-- Create payment_methods table
CREATE TABLE IF NOT EXISTS payment_methods (
    payment_method_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL,
    provider_token VARCHAR(255) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    last4 VARCHAR(4) NOT NULL,
    expiry_month INTEGER NOT NULL,
    expiry_year INTEGER NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_payment_methods PRIMARY KEY (payment_method_id),
    CONSTRAINT fk_payment_methods_customer_id FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

CREATE INDEX idx_payment_methods_customer_id ON payment_methods (customer_id);

-- Create password_reset_tokens table
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    token_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (token_id),
    CONSTRAINT fk_password_reset_tokens_customer_id FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE,
    CONSTRAINT uq_password_reset_tokens_token UNIQUE (token)
);

CREATE INDEX idx_password_reset_tokens_customer_id ON password_reset_tokens (customer_id);
CREATE INDEX idx_password_reset_tokens_token ON password_reset_tokens (token);

-- Create notification_preferences table
CREATE TABLE IF NOT EXISTS notification_preferences (
    customer_id INTEGER NOT NULL,
    email_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sms_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    push_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_notification_preferences PRIMARY KEY (customer_id),
    CONSTRAINT fk_notification_preferences_customer_id FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

-- Create preferences table
CREATE TABLE IF NOT EXISTS preferences (
    customer_id INTEGER NOT NULL,
    preferred_language VARCHAR(5) NOT NULL DEFAULT 'EN',
    preferred_currency VARCHAR(5) NOT NULL DEFAULT 'EGP',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_preferences PRIMARY KEY (customer_id),
    CONSTRAINT fk_preferences_customer_id FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE,
    CONSTRAINT chk_preferences_language CHECK (preferred_language IN ('EN', 'AR')),
    CONSTRAINT chk_preferences_currency CHECK (preferred_currency IN ('EGP', 'USD'))
);
