CREATE TABLE IF NOT EXISTS language (
    language_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    language_name VARCHAR(100) NOT NULL,
    language_code VARCHAR(10) NOT NULL,
    language_icon_url VARCHAR(500),
    CONSTRAINT pk__language PRIMARY KEY (language_id),
    CONSTRAINT uq__language__language_code UNIQUE (language_code)
);

CREATE TABLE IF NOT EXISTS user_type (
    user_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_type_name VARCHAR(100) NOT NULL,
    user_type_description TEXT,
    CONSTRAINT pk__user_type PRIMARY KEY (user_type_id),
    CONSTRAINT uq__user_type__user_type_name UNIQUE (user_type_name)
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_type_id INTEGER NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    user_phone_number VARCHAR(50) NOT NULL,
    user_first_name VARCHAR(100),
    user_last_name VARCHAR(100),
    user_language_id INTEGER NOT NULL,
    user_password_hash VARCHAR(255) NOT NULL,
    user_joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_last_login_at TIMESTAMPTZ,
    user_last_login_status VARCHAR(50),
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk__users PRIMARY KEY (user_id),
    CONSTRAINT fk__users__user_type_id FOREIGN KEY (user_type_id) REFERENCES user_type (user_type_id) ON DELETE RESTRICT,
    CONSTRAINT fk__users__user_language_id FOREIGN KEY (user_language_id) REFERENCES language (language_id) ON DELETE RESTRICT,
    CONSTRAINT uq__users__user_email UNIQUE (user_email),
    CONSTRAINT uq__users__user_phone_number UNIQUE (user_phone_number)
);

CREATE TABLE IF NOT EXISTS customer (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    customer_notification_status BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk__customer PRIMARY KEY (customer_id),
    CONSTRAINT fk__customer__user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT uq__customer__user_id UNIQUE (user_id)
);

CREATE INDEX idx__users__user_type_id ON users (user_type_id);
CREATE INDEX idx__users__user_language_id ON users (user_language_id);

INSERT INTO language (language_name, language_code, language_icon_url)
VALUES
    ('English', 'en', NULL),
    ('Arabic', 'ar', NULL);

INSERT INTO user_type (user_type_name, user_type_description)
VALUES
    ('customer', 'Regular end-user customer'),
    ('admin', 'System administrator');