CREATE TABLE IF NOT EXISTS restaurant (
    restaurant_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    restaurant_name VARCHAR(150) NOT NULL,
    restaurant_phone VARCHAR(50),
    restaurant_email VARCHAR(255),
    restaurant_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk__restaurant PRIMARY KEY (restaurant_id),
    CONSTRAINT uq__restaurant__restaurant_name UNIQUE (restaurant_name)
);

CREATE TABLE IF NOT EXISTS item_category (
    item_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    item_category_name VARCHAR(100) NOT NULL,
    CONSTRAINT pk__item_category PRIMARY KEY (item_category_id),
    CONSTRAINT uq__item_category__item_category_name UNIQUE (item_category_name)
);

CREATE TABLE IF NOT EXISTS menu (
    menu_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id INTEGER NOT NULL,
    menu_name VARCHAR(150) NOT NULL,
    menu_icon VARCHAR(255),
    menu_ui_order INTEGER NOT NULL DEFAULT 0,
    menu_is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk__menu PRIMARY KEY (menu_id),
    CONSTRAINT fk__menu__restaurant_id FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS menu_item (
    menu_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    menu_id INTEGER NOT NULL,
    menu_item_category_id INTEGER,
    menu_item_name VARCHAR(150) NOT NULL,
    menu_item_image VARCHAR(255),
    menu_item_price NUMERIC(10,2) NOT NULL,
    menu_item_available_quantity INTEGER,
    menu_item_on_demand_status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE',
    CONSTRAINT pk__menu_item PRIMARY KEY (menu_item_id),
    CONSTRAINT fk__menu_item__menu_id FOREIGN KEY (menu_id) REFERENCES menu (menu_id) ON DELETE CASCADE,
    CONSTRAINT fk__menu_item__item_category_id FOREIGN KEY (menu_item_category_id) REFERENCES item_category (item_category_id) ON DELETE SET NULL,
    CONSTRAINT chk__menu_item__menu_item_price CHECK (menu_item_price >= 0),
    CONSTRAINT chk__menu_item__menu_item_available_quantity CHECK (menu_item_available_quantity IS NULL OR menu_item_available_quantity >= 0)
);

CREATE INDEX idx__menu__item_menu_id ON menu_item (menu_id);
CREATE INDEX idx__menu__item_restaurant_id ON menu_item (restaurant_id);
CREATE INDEX idx__menu__item_category_id ON menu_item (menu_item_category_id);