CREATE TABLE IF NOT EXISTS cart (
    cart_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL,
    restaurant_id INTEGER NOT NULL,
    cart_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk__cart PRIMARY KEY (cart_id),
    CONSTRAINT fk__cart__customer_id FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE,
    CONSTRAINT fk__cart__restaurant_id FOREIGN KEY (restaurant_id) REFERENCES restaurant (restaurant_id) ON DELETE CASCADE,
    CONSTRAINT uq__cart__customer_id UNIQUE (customer_id)
);

CREATE TABLE IF NOT EXISTS cart_item (
    cart_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cart_id INTEGER NOT NULL,
    menu_item_id INTEGER NOT NULL,
    cart_item_price NUMERIC(10,2) NOT NULL,
    cart_item_quantity INTEGER NOT NULL DEFAULT 1,
    cart_item_note TEXT,
    CONSTRAINT pk__cart_item PRIMARY KEY (cart_item_id),
    CONSTRAINT fk__cart_item__cart_id FOREIGN KEY (cart_id) REFERENCES cart (cart_id) ON DELETE CASCADE,
    CONSTRAINT fk__cart_item__menu_item_id FOREIGN KEY (menu_item_id) REFERENCES menu_item (menu_item_id) ON DELETE CASCADE,
    CONSTRAINT chk__cart_item__cart_item_price CHECK (cart_item_price >= 0),
    CONSTRAINT chk__cart_item__cart_item_quantity CHECK (cart_item_quantity > 0)
);

CREATE INDEX idx__cart__restaurant_id ON cart (restaurant_id);
CREATE INDEX idx__cart__item_cart_id ON cart_item (cart_id);
CREATE INDEX idx__cart__item_menu_item_id ON cart_item (menu_item_id);